package me.tewodros.dael.audio

import android.content.Context
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.os.Handler
import android.os.Looper
import android.speech.tts.TextToSpeech
import android.speech.tts.UtteranceProgressListener
import android.speech.tts.Voice
import androidx.compose.runtime.staticCompositionLocalOf
import java.util.Locale

/**
 * Says a phrase. Prefers a bundled natural-voice clip (generated by tools/gen_voices.py and
 * looked up by a slug of the exact text); falls back to the system text-to-speech engine.
 */
class Speaker(context: Context) {
    private val app = context.applicationContext
    private var ready = false
    private lateinit var tts: TextToSpeech
    private var player: MediaPlayer? = null
    private val mainHandler = Handler(Looper.getMainLooper())

    init {
        tts = TextToSpeech(app) { status ->
            ready = status == TextToSpeech.SUCCESS
            if (ready) {
                tts.language = Locale.getDefault()
                tts.setSpeechRate(0.9f)
                pickBestVoice()
            }
        }
    }

    /** Chooses the highest quality offline voice available, which beats the default on most phones. */
    private fun pickBestVoice() {
        val lang = Locale.getDefault().language
        val best = runCatching { tts.voices }.getOrNull()
            ?.filter { it.locale.language == lang && !it.isNetworkConnectionRequired && !it.features.contains(TextToSpeech.Engine.KEY_FEATURE_NOT_INSTALLED) }
            ?.maxByOrNull { it.quality * 10 + if (it.name.contains("female", true)) 1 else 0 }
        if (best != null && best.quality >= Voice.QUALITY_HIGH) tts.voice = best
    }

    fun say(text: String, interrupt: Boolean = true, onDone: (() -> Unit)? = null) {
        val resId = app.resources.getIdentifier(slug(text), "raw", app.packageName)
        if (resId != 0) {
            playRaw(resId, interrupt, onDone)
            return
        }
        if (!ready) { onDone?.invoke(); return }
        val mode = if (interrupt) TextToSpeech.QUEUE_FLUSH else TextToSpeech.QUEUE_ADD
        val id = text.hashCode().toString()
        if (onDone != null) {
            tts.setOnUtteranceProgressListener(object : UtteranceProgressListener() {
                override fun onStart(utteranceId: String?) {}
                override fun onError(utteranceId: String?) { if (utteranceId == id) mainHandler.post(onDone) }
                override fun onDone(utteranceId: String?) { if (utteranceId == id) mainHandler.post(onDone) }
            })
        }
        tts.speak(text, mode, null, id)
    }

    /** Plays a bundled sound effect such as a real animal recording (res/raw/s_<key>.ogg). */
    fun sound(key: String, interrupt: Boolean = true, onDone: (() -> Unit)? = null) {
        val resId = app.resources.getIdentifier("s_$key", "raw", app.packageName)
        if (resId == 0) { onDone?.invoke(); return }
        playRaw(resId, interrupt, onDone)
    }

    /** Says a name, then plays its sound, then runs [onDone]. Used by the animal game and pretend calls. */
    fun sayThenSound(text: String, soundKey: String, onDone: (() -> Unit)? = null) {
        say(text) { sound(soundKey, interrupt = false, onDone = onDone) }
    }

    private fun playRaw(resId: Int, interrupt: Boolean, onDone: (() -> Unit)?) {
        if (interrupt) stop()
        val mp = MediaPlayer.create(app, resId, AudioAttributes.Builder()
            .setUsage(AudioAttributes.USAGE_MEDIA)
            .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
            .build(), 0)
        if (mp == null) { onDone?.invoke(); return }
        player = mp
        mp.setOnCompletionListener {
            it.release()
            if (player === it) player = null
            onDone?.invoke()
        }
        mp.start()
    }

    fun stop() {
        player?.let { runCatching { it.stop(); it.release() } }
        player = null
        if (ready) tts.stop()
    }

    fun shutdown() {
        stop()
        tts.shutdown()
    }

    companion object {
        /** Must match slug() in tools/gen_voices.py. */
        fun slug(text: String): String {
            val s = text.lowercase().replace(Regex("[^a-z0-9]+"), "_").trim('_')
            return "v_" + s.take(60).trimEnd('_')
        }
    }
}

val LocalSpeaker = staticCompositionLocalOf<Speaker> { error("Speaker not provided") }
